# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := ProjectR.Model ProjectR.Logic ProjectR.MapGen ProjectR.View ProjectR

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

ProjectR.Model: 
	@echo "==== Building ProjectR.Model ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectR.Model.make

ProjectR.Logic: ProjectR.Model
	@echo "==== Building ProjectR.Logic ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectR.Logic.make

ProjectR.MapGen: ProjectR.Model
	@echo "==== Building ProjectR.MapGen ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectR.MapGen.make

ProjectR.View: ProjectR.Model
	@echo "==== Building ProjectR.View ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectR.View.make

ProjectR: ProjectR.Model ProjectR.Logic ProjectR.View ProjectR.MapGen
	@echo "==== Building ProjectR ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ProjectR.make

clean:
	@${MAKE} --no-print-directory -C . -f ProjectR.Model.make clean
	@${MAKE} --no-print-directory -C . -f ProjectR.Logic.make clean
	@${MAKE} --no-print-directory -C . -f ProjectR.MapGen.make clean
	@${MAKE} --no-print-directory -C . -f ProjectR.View.make clean
	@${MAKE} --no-print-directory -C . -f ProjectR.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ProjectR.Model"
	@echo "   ProjectR.Logic"
	@echo "   ProjectR.MapGen"
	@echo "   ProjectR.View"
	@echo "   ProjectR"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
